# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sergio/Proyectos/modpapi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sergio/Proyectos/modpapi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergio/Proyectos/modpapi/CMakeFiles /home/sergio/Proyectos/modpapi/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergio/Proyectos/modpapi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mod_papi

# Build rule for target.
mod_papi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_papi
.PHONY : mod_papi

# fast build rule for target.
mod_papi/fast:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/build
.PHONY : mod_papi/fast

# target to build an object file
mod_papi.o:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi.o
.PHONY : mod_papi.o

# target to preprocess a source file
mod_papi.i:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi.i
.PHONY : mod_papi.i

# target to generate assembly for a file
mod_papi.s:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi.s
.PHONY : mod_papi.s

# target to build an object file
mod_papi_config.o:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_config.o
.PHONY : mod_papi_config.o

# target to preprocess a source file
mod_papi_config.i:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_config.i
.PHONY : mod_papi_config.i

# target to generate assembly for a file
mod_papi_config.s:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_config.s
.PHONY : mod_papi_config.s

# target to build an object file
mod_papi_cookie_handler.o:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_cookie_handler.o
.PHONY : mod_papi_cookie_handler.o

# target to preprocess a source file
mod_papi_cookie_handler.i:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_cookie_handler.i
.PHONY : mod_papi_cookie_handler.i

# target to generate assembly for a file
mod_papi_cookie_handler.s:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_cookie_handler.s
.PHONY : mod_papi_cookie_handler.s

# target to build an object file
mod_papi_crypt.o:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_crypt.o
.PHONY : mod_papi_crypt.o

# target to preprocess a source file
mod_papi_crypt.i:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_crypt.i
.PHONY : mod_papi_crypt.i

# target to generate assembly for a file
mod_papi_crypt.s:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_crypt.s
.PHONY : mod_papi_crypt.s

# target to build an object file
mod_papi_poa.o:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_poa.o
.PHONY : mod_papi_poa.o

# target to preprocess a source file
mod_papi_poa.i:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_poa.i
.PHONY : mod_papi_poa.i

# target to generate assembly for a file
mod_papi_poa.s:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_poa.s
.PHONY : mod_papi_poa.s

# target to build an object file
mod_papi_post_handler.o:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_post_handler.o
.PHONY : mod_papi_post_handler.o

# target to preprocess a source file
mod_papi_post_handler.i:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_post_handler.i
.PHONY : mod_papi_post_handler.i

# target to generate assembly for a file
mod_papi_post_handler.s:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_post_handler.s
.PHONY : mod_papi_post_handler.s

# target to build an object file
mod_papi_redirect_gpoa.o:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_redirect_gpoa.o
.PHONY : mod_papi_redirect_gpoa.o

# target to preprocess a source file
mod_papi_redirect_gpoa.i:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_redirect_gpoa.i
.PHONY : mod_papi_redirect_gpoa.i

# target to generate assembly for a file
mod_papi_redirect_gpoa.s:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_redirect_gpoa.s
.PHONY : mod_papi_redirect_gpoa.s

# target to build an object file
mod_papi_utils.o:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_utils.o
.PHONY : mod_papi_utils.o

# target to preprocess a source file
mod_papi_utils.i:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_utils.i
.PHONY : mod_papi_utils.i

# target to generate assembly for a file
mod_papi_utils.s:
	$(MAKE) -f CMakeFiles/mod_papi.dir/build.make CMakeFiles/mod_papi.dir/mod_papi_utils.s
.PHONY : mod_papi_utils.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... mod_papi"
	@echo "... rebuild_cache"
	@echo "... mod_papi.o"
	@echo "... mod_papi.i"
	@echo "... mod_papi.s"
	@echo "... mod_papi_config.o"
	@echo "... mod_papi_config.i"
	@echo "... mod_papi_config.s"
	@echo "... mod_papi_cookie_handler.o"
	@echo "... mod_papi_cookie_handler.i"
	@echo "... mod_papi_cookie_handler.s"
	@echo "... mod_papi_crypt.o"
	@echo "... mod_papi_crypt.i"
	@echo "... mod_papi_crypt.s"
	@echo "... mod_papi_poa.o"
	@echo "... mod_papi_poa.i"
	@echo "... mod_papi_poa.s"
	@echo "... mod_papi_post_handler.o"
	@echo "... mod_papi_post_handler.i"
	@echo "... mod_papi_post_handler.s"
	@echo "... mod_papi_redirect_gpoa.o"
	@echo "... mod_papi_redirect_gpoa.i"
	@echo "... mod_papi_redirect_gpoa.s"
	@echo "... mod_papi_utils.o"
	@echo "... mod_papi_utils.i"
	@echo "... mod_papi_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

